namespace WalksAPI.Models.Domain.DTOs
{
    public class AddRegionRequestDTO
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string? RegionImageUrl { get; set; }

        // Note: The Id is not included here as it will be generated by the database.
        // If you want to include it, you can add it, but typically it's not part of the request DTO.
    }
}
